# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d4c3b3c346131e2b41abc0ef8cdf61ac2cf517ad49fbed141fe12672e0d7a15d476dc6477ada5c3464abd010ebc42692e51252049121d41a64e960497c4450

test:
  secret_key_base: 2f684c2c9b1a899999a9aacdbb4a49fbdd7c8670f28b3fb6e18fe42377186a6b4fbe90737f9e9a3f7e93312b7f03bb3be93fe513e6f84f02c18d18d19d8108d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
